language: en-US
tone_instructions: ''
early_access: false
enable_free_tier: true
reviews:
  profile: assertive
  request_changes_workflow: false  # Approve the review once CodeRabbit's comments are resolved. 
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: '@coderabbitai'
  auto_title_instructions: ''
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: false
  sequence_diagrams: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: false
  poem: false
  labeling_instructions: []
  path_filters: []
  path_instructions:
    - path: '**'
      instructions: |
        - Focus on code quality, readability, and maintainability.
        - Flag any potential security vulnerabilities.
        - Suggest improvements for performance optimization.
        - Ensure no sensitive information (e.g., API keys) is exposed.
        - Follow WordPress coding standards for PHP, HTML, CSS, and JavaScript.

    - path: '**/*.js'
      instructions: |
        Review the JavaScript code against:
          - ESLint

    - path: '**/*.css'
      instructions: |
        Review the CSS code against:
          - Stylelint
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches: []
  finishing_touches:
    docstrings:
      enabled: true
  tools:
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_only: false
      level: default
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
    phpstan:
      enabled: true
      level: default
    golangci-lint:
      enabled: false
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: false
    eslint:
      enabled: true
    rubocop:
      enabled: false
    buf:
      enabled: false
    regal:
      enabled: false
    actionlint:
      enabled: true
    pmd:
      enabled: false
    cppcheck:
      enabled: false
    semgrep:
      enabled: true
    circleci:
      enabled: false
chat:
  auto_reply: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: auto
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  learnings:
    scope: global
  issues:
    scope: local
  jira:
    usage: disabled
    project_keys: []
  linear:
    usage: disabled
    team_keys: []
  pull_requests:
    scope: global
code_generation:
  docstrings:
    language: en-US